CREATE SEQUENCE "weathers_id_seq"
    MINVALUE 1
    MAXVALUE 10000
    INCREMENT BY 10
    START WITH 1
    NOCACHE
NOCYCLE;

create table weathers
(
    id bigint generated by default as identity primary key,
    country text not null,
    city text not null,
    published_date timestamp,
    temp float not null
);

